name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go 1.26
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '1.26.0-rc.1'

      - name: Run tests
        env:
          GOEXPERIMENT: simd
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go 1.26
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '1.26.0-rc.1'

      - name: Install golangci-lint v2
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Run golangci-lint
        env:
          GOEXPERIMENT: simd
        run: golangci-lint run

