name: tagpr

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      # Make tagpr execution results available to other jobs
      tag-name: ${{ steps.run-tagpr.outputs.tag-name }}
      tag-created: ${{ steps.run-tagpr.outputs.tag-created }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run tagpr
        id: run-tagpr
        uses: Songmu/tagpr@6423eaf899ec18cb0f5ad3e5c3a7482595a62f04 # v1.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
